language: ruby
rvm:
- 2.1.5
addons:
  postgresql: "9.3"
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate
# - bundle exec rake db:test:prepare
  - bundle exec rake test
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database pdb_test;' -U postgres
  - psql -U postgres -c "create extension postgis"

bundler_args: --binstubs=./bundler_stubs
sudo: false
branches:
  only:
    - develop
